### ISSUE TITLE
Missing blocks in render

### ISSUE THREAD

**Issue by rawbits2010** [tectonicus/tectonicus#149] opened 2021-04-03 17:33 UTC
There are some weird missing blocks in the frozen ocean - not the grid issue (have that also on some runs though).
I flew there and there is lava in a ravine below the ocean where is a clear drop rendered on the map. And there are some blocks missing on see level which is happened to be plain ice.
![Tectonicus_missing_blocks_bug](https://user-images.githubusercontent.com/25568847/113486437-08a4b180-94b3-11eb-8eb3-d46a9955277b.png)
![2021-04-03_19 24 29](https://user-images.githubusercontent.com/25568847/113486446-1d814500-94b3-11eb-82cf-10d2e2a87fee.png)
![2021-04-03_19 24 53](https://user-images.githubusercontent.com/25568847/113486451-23772600-94b3-11eb-9251-825ca4d4d89e.png)

**Comment by skoeven** [comment] 2022-03-03 04:29
The bubble column blocks have been fixed in 0370b7c0ecf1450933cdfc94e35e3e3ad7862ed2

The visually glitched plain ice blocks are caused by the same underlying issue as the ice grid (issue #32) which is that translucent objects won't blend correctly unless they are sorted back to front.  We sort chunks back to front before rendering but need to do the same for individual translucent blocks in order to fix these problems.

**Comment by skoeven** [comment] 2022-03-11 05:45
Closing this issue as the missing block has been resolved.  The ice issue is not fixed but it is much trickier. Any updates for that will be in issue #32

**Closed by skoeven** 2022-03-11 05:45 UTC
Labels: bug
