### ISSUE TITLE
Placed Ender Dragon head causes map generation failure/Java Exception.

### ISSUE THREAD

**Issue by turtle2472** [tectonicus/tectonicus#66] opened 2016-03-31 01:50 UTC
`FindChangedTiles took: 42.467 seconds
RenderBaseTiles
Base render is at zoom 23 with 512x512 tiles
RenderBaseTiles
java.lang.NullPointerExceptionof 63)
    at tectonicus.blockTypes.Skull.addEdgeGeometry(Skull.java:136)
    at tectonicus.blockTypes.Skull.addInteriorGeometry(Skull.java:77)
    at tectonicus.Chunk.createGeometry(Chunk.java:123)
    at tectonicus.world.World.draw(World.java:524)
    at tectonicus.world.World.draw(World.java:471)
    at tectonicus.TileRenderer.renderBaseTiles(TileRenderer.java:652)
    at tectonicus.TileRenderer.output(TileRenderer.java:297)
    at tectonicus.TectonicusApp.run(TectonicusApp.java:925)
    at tectonicus.TectonicusApp.main(TectonicusApp.java:1173)
Cleaning up...`

When the generation run encounters the skull it fails and prints the above exception.  This is confirmed by removing the placed dragon head and maps process correctly.  When the head is a placed block the map generation fails, when the head is removed and put in an inventory somewhere the maps process normally.

`+ + + + + + + + + + + + + + + + + + + + + + +`
`Tectonicus
   Version: 2.22
   Build null
   Constructed on March 29 2016 at 2234`
`+ + + + + + + + + + + + + + + + + + + + + + +`
`Started on Wed Mar 30 21:27:27 EDT 2016
System:
    OS Name: Mac OS X
    OS Architecture: x86_64
    OS Version: 10.9.5
    Java vendor: Oracle Corporation
    Java version: 1.8.0_77
    Awt toolkit: sun.lwawt.macosx.LWCToolkit
    Headless?: null
`

Please let me know if you need more information.

**Comment by skoeven** [comment] 2016-03-31 04:12
The NullPointerException means that it can't find the Ender Dragon texture file.  Two things you can check quickly:  
- make sure you are using a Minecraft 1.9 jar file or 1.9 texture pack
- if you use a custom BlockConfig update the Skull element with the 'dtexture' attribute and path to the Ender Dragon texture file

**Comment by turtle2472** [comment] 2016-03-31 04:51
I am running 1.9 and a custom texture pack for 1.9.  The head shows in the game normally so I would assume it's in the texture pack right but I don't build the texture pack, another admin on the server does.  We do not use custom blocks, it's vanilla MC.  Is there something I should check specifically?

**Comment by skoeven** [comment] 2016-03-31 05:44
If Tectonicus can't find the texture in the custom texture pack it should just fall back to the original Minecraft jar version.  Could you post the entirety of both your log and config files?  I want to take a look to see if I can spot anything else.

**Comment by skoeven** [comment] 2016-03-31 06:10
I just realized what might be causing this.  Tectonicus tries to figure out what version of texture pack it's using so that it knows which defaultBlockConfig file to look in for texture file names.  Specifically, it checks the texture pack for the file "assets/minecraft/textures/blocks/redstone_dust_cross.png".  This texture no longer exists in 1.9, but maybe it's still in your custom texture pack?  If it is, then Tectonicus treats it like a 1.8 texture pack and won't look for the Ender Dragon texture.

**Comment by turtle2472** [comment] 2016-03-31 17:04
The file "assets/minecraft/textures/blocks/redstone_dust_cross.png" was still in the texture pack.  I've renamed it and am running the maps now to see how it handles generating the maps now.  It will take a day or two to run the maps so I'll post an update once they've completed.

**Comment by turtle2472** [comment] 2016-03-31 17:10
BTW, I keep forgetting to say this.  Thank you very much **skoeven** for keeping this project going.  My players and I all really appreciate the work you've carried on.

**Comment by skoeven** [comment] 2016-03-31 22:28
Thanks!  I've enjoyed working on it when I have the time.

As an aside, could you post your log file(s) for your maps once you are done?  I've been looking into trying to improve Tectonicus' speed and it's nice to have a benchmark especially for large maps.

**Comment by turtle2472** [comment] 2016-04-02 05:35
I will be happy to post those files for you but I had to start over.  It's going to be a few days again.  I changed the texture pack and it's clearing the cache.  I'll upload them when they are done.  My maps actually render seven different layers which is what makes it take so long.  It's only a ~650MB world folder.

**Comment by infinitewarp** [comment] 2016-04-02 19:44
I'm finding the same problem, but I'm *not* using a custom resource/texture pack in my config. I have configured to use the latest 1.9.2 minecraft jar, and I'm using the same version and build of Tectonicus as turtle2472.

Processing eventually raises NPE in the same place when a dragon skull is found:
```
java.lang.NullPointerException
	at tectonicus.blockTypes.Skull.addEdgeGeometry(Skull.java:136)
	at tectonicus.Chunk.createGeometry(Chunk.java:119)
	at tectonicus.world.World.draw(World.java:524)
	at tectonicus.world.World.draw(World.java:471)
	at tectonicus.TileRenderer.renderBaseTiles(TileRenderer.java:652)
	at tectonicus.TileRenderer.output(TileRenderer.java:297)
	at tectonicus.TectonicusApp.run(TectonicusApp.java:925)
	at tectonicus.TectonicusApp.main(TectonicusApp.java:1173)
```

Shortly after this exception is raised, it appears to abort processing, prints the following lines to console, and then the java process hangs indefinitely and needs to be killed.
```
Cleaning up...
Writing player skin cache info (37 skins to write)
100%
Player skin cache written
Finished
```

Much earlier in the logs, it also raises an NPE upon failing to find the command block textures. This would suggest to me that it doesn't understand that it should be working with Minecraft 1.9 resources because the command blocks changed in 1.9:
```
assets/minecraft/textures/blocks/command_block.png
java.io.FileNotFoundException: assets/minecraft/textures/blocks/command_block.png (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at tectonicus.texture.TexturePack.loadTexture(TexturePack.java:422)
	at tectonicus.texture.TexturePack.findTexture(TexturePack.java:352)
	at tectonicus.texture.TexturePack.findTexture(TexturePack.java:286)
	at tectonicus.BlockRegistryParser.parseTexture(BlockRegistryParser.java:838)
	at tectonicus.BlockRegistryParser.parse(BlockRegistryParser.java:199)
	at tectonicus.BlockRegistryParser.parse(BlockRegistryParser.java:137)
	at tectonicus.world.World.loadBlockRegistry(World.java:208)
	at tectonicus.TileRenderer.setupWorldForLayer(TileRenderer.java:389)
	at tectonicus.TileRenderer.output(TileRenderer.java:281)
	at tectonicus.TectonicusApp.run(TectonicusApp.java:925)
	at tectonicus.TectonicusApp.main(TectonicusApp.java:1173)
Error: Couldn't load assets/minecraft/textures/blocks/command_block.png
Error while parsing [Solid: null]
java.lang.NullPointerException
	at tectonicus.texture.TexturePack.findTexture(TexturePack.java:288)
	at tectonicus.BlockRegistryParser.parseTexture(BlockRegistryParser.java:838)
	at tectonicus.BlockRegistryParser.parse(BlockRegistryParser.java:199)
	at tectonicus.BlockRegistryParser.parse(BlockRegistryParser.java:137)
	at tectonicus.world.World.loadBlockRegistry(World.java:208)
	at tectonicus.TileRenderer.setupWorldForLayer(TileRenderer.java:389)
	at tectonicus.TileRenderer.output(TileRenderer.java:281)
	at tectonicus.TectonicusApp.run(TectonicusApp.java:925)
	at tectonicus.TectonicusApp.main(TectonicusApp.java:1173)
```

**Comment by turtle2472** [comment] 2016-04-02 19:44
These are the logs I have from a completed render of the seven layers.

[backup.log.txt](https://github.com/tectonicus/tectonicus/files/200999/backup.log.txt)
[Tectonicus.log.txt](https://github.com/tectonicus/tectonicus/files/201000/Tectonicus.log.txt)

The texture pack we use can be found here: http://applenova.com/etc/brad/minecraft/AppleNovaBradTextures.zip

The other admin is working with this now trying to figure out why it wasn't rendering right....  In fact he just posted above this one as I was posting here.

**Comment by infinitewarp** [comment] 2016-04-02 21:54
I did a little more digging with the resource pack, and it does look like the problem is the presence of the `redstone_dust_cross.png` file. I never would have expected the presence of an old file to cause such a critical failure like this, but after reading your TexturePack class, now I understand why. I'm glad you at least have that TODO in there. :) I guess you can close this issue, but I'd also suggest a couple of possible additions:

- Since the version detection is so critical, maybe allow it to be configured explicitly? Or log the detected version in TexturePack's constructor?
- If I'm reading ZipStack.java and TexturePack.java correctly, it seems like they are too aggressive about finding these files. TexturePack will fall back to the oldest possible version between minecraftJar and texturePack. What would your thoughts be on exclusively looking at an instance of ZipStack containing *only* minecraftJar to detect the authoritative version?
- Alternatively, what are your thoughts on reading the contents of pack.mcmeta and looking at pack_format?
- Assuming no changes to the version detection, would it be reasonable to omit objects/blocks from rendering if you fail to load its information?

**Comment by turtle2472** [comment] 2016-04-02 22:54
These are the logs for a normal incremental update of the maps that is able to use the cache:
[backup.log.txt](https://github.com/tectonicus/tectonicus/files/201072/backup.log.txt)
[Tectonicus.log.txt](https://github.com/tectonicus/tectonicus/files/201073/Tectonicus.log.txt)

**Comment by turtle2472** [comment] 2016-04-02 22:57
These are the logs from a normal incremental build where the cache was used and minor map data changes:
[backup.log.txt](https://github.com/tectonicus/tectonicus/files/201075/backup.log.txt)
[Tectonicus.log.txt](https://github.com/tectonicus/tectonicus/files/201076/Tectonicus.log.txt)

**Comment by turtle2472** [comment] 2016-04-02 23:29
Using infinitewarp's package.sh on the texture pack I have and removing both the `redstone_dust_cross.png` and `redstone_dust_cross_overlay.png` seems to have worked in letting the maps render using our custom textures.

**Closed** 2024-03-27 03:38 UTC
