### ISSUE TITLE
`mode="cmd"` still tries to open a display on MacOS

### ISSUE THREAD

**Issue by rjp** [tectonicus/tectonicus#153] opened 2021-05-28 13:33 UTC
```
Initialising display...
GLFW error [0x00010008]: Cocoa: Failed to find service port for display
2021-05-28 14:29:45.875 java[7240:5876052] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000019fcb0c68 __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x000000019f9d90a8 objc_exception_throw + 60
... some lines elided ...
	21  libjli.dylib                        0x0000000104405a20 JavaMain + 2868
	22  libsystem_pthread.dylib             0x000000019fb33878 _pthread_start + 320
	23  libsystem_pthread.dylib             0x000000019fb2e5e0 thread_start + 8
)
libc++abi: terminating with uncaught exception of type NSException
Abort trap: 6
```

`mode="gui"` correctly opens a GUI.

Same happens with `OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)` (default MacOS Java install) and `OpenJDK Runtime Environment Zulu11.43+1007-CA (build 11.0.9.1+1-LTS)` (Zulu's ARM64.)

**Comment by skoeven** [comment] 2021-06-15 04:49
Duplicate of #137

**Closed by skoeven** 2021-06-15 04:49 UTC
