### ISSUE TITLE
While rendering new tiles error loading chunk seems to stop all rendering

### ISSUE THREAD

**Issue by turtle2472** [tectonicus/tectonicus#122] opened 2020-10-08 12:42 UTC
During the initial phase of rendering there consistently fails to complete the render.  It will go along like this:
```
FindChangedTiles took: 118.741 seconds
Render Base Tiles
Base render is at zoom 23 with 512x512 tiles
Rendering tile @ 125,62 (tile 752 of 92234)
```
Then after a while I come back and it always looks like this:
```
...
Outputted 19 beds
Writing portals...
Wrote 0 portals
Writing views...
Writing chests to /home/turtle/working/MCMaps/an/Map0/chests.js
Finding changed views...
Found 0 changed views (out of 0 total views)
Drawing Day views...
Drawing Night views...
View rendering done!
Creating block registry
Loading all block state and block model json files...
All json files loaded.
Tile cache directory found and is valid. Using cache at /home/turtle/working/MCMaps/an/Cache/tileHashes/Map0/LayerA
100%
FindChangedTiles took: 103.057 seconds
Render Base Tiles
Base render is at zoom 23 with 512x512 tiles
Error while trying to load chunk at (83, -5) from region /home/turtle/working/tectonicus/world/region/r.2.-1.mca
java.lang.NullPointerException
Error while trying to load chunk at (82, -3) from region /home/turtle/working/tectonicus/world/region/r.2.-1.mca
java.lang.NullPointerException
Error while trying to load chunk at (84, -3) from region /home/turtle/working/tectonicus/world/region/r.2.-1.mca
java.lang.NullPointerException
Error while trying to load chunk at (85, -3) from region /home/turtle/working/tectonicus/world/region/r.2.-1.mca
java.lang.NullPointerException
Error while trying to load chunk at (82, -4) from region /home/turtle/working/tectonicus/world/region/r.2.-1.mca
java.lang.NullPointerException
Error while trying to load chunk at (84, -4) from region /home/turtle/working/tectonicus/world/region/r.2.-1.mca
java.lang.NullPointerException
Error while trying to load chunk at (83, -2) from region /home/turtle/working/tectonicus/world/region/r.2.-1.mca
java.lang.NullPointerException
Error while trying to load chunk at (84, -2) from region /home/turtle/working/tectonicus/world/region/r.2.-1.mca
java.lang.NullPointerException
Error while trying to load chunk at (85, -2) from region /home/turtle/working/tectonicus/world/region/r.2.-1.mca
java.lang.NullPointerException
Error while trying to load chunk at (86, -2) from region /home/turtle/working/tectonicus/world/region/r.2.-1.mca
java.lang.NullPointerException
java.lang.NullPointerException
        at tectonicus.Chunk.getBiomeId(Unknown Source)
        at tectonicus.world.World.getBiomeId(Unknown Source)
        at tectonicus.world.World.getWaterColor(Unknown Source)
        at tectonicus.blockTypes.Water.addEdgeGeometry(Unknown Source)
        at tectonicus.Chunk.createGeometry(Unknown Source)
        at tectonicus.world.World.draw(Unknown Source)
        at tectonicus.world.World.draw(Unknown Source)
        at tectonicus.TileRenderer.renderBaseTiles(Unknown Source)
        at tectonicus.TileRenderer.output(Unknown Source)
        at tectonicus.TectonicusApp.run(Unknown Source)
        at tectonicus.TectonicusApp.main(Unknown Source)
Cleaning up...
Writing player skin cache info (19 skins to write)
100%
Player skin cache written
Finished
```
We run a vanilla server but there are a few command blocks that I know of.  I'm planning to test this on a different machine and with a trimmed down config.xml, but even still out world is pretty big.

**Comment by skoeven** [comment] 2020-10-09 02:54
It looks like it can't find biome IDs for a bunch of water blocks.  I'm assuming this is a 1.16 world? Did you create the world new in 1.16 or has it gone through different versions of Minecraft?

**Comment by turtle2472** [comment] 2020-10-09 13:21
We are running 1.16.3.jar with no mods, just plain vanilla.  This world has been around a long time.  I think it started back near 1.6 or so.  Around 2013 was this world's start.

**Comment by skoeven** [comment] 2020-10-10 00:48
Well, I've tried a bunch of stuff but can't seem to reproduce what you're seeing.  Would it be possible to get a copy of one of the region files that's throwing errors?  Also, I probably won't have time until Monday to look into this more just FYI.

**Comment by turtle2472** [comment] 2020-10-11 14:48
Here you go.  Hopefully this can help you figure out what is going on.
[r.2.-1.mca.zip](https://github.com/tectonicus/tectonicus/files/5361284/r.2.-1.mca.zip)

Is it possible the have Tectonicus not die on an error like that?  Like maybe render what it can be leave blocks blank that it can't interpret? It should log that I would think so it could be resolved for a full render I would think though.

Given I'm not really a coder I'm not sure of the technical side of what I'm asking you to do, it just seems like it would be better to produce something rather than die.

**Comment by skoeven** [comment] 2020-10-13 15:12
It is possible for Tectonicus to work around errors it just depends on the error.  In this case it was caused by a bad assumption that the Name tag would always exist for player heads, and when it couldn't find it it was causing a worse failure than it should have.  I don't know if it was always possible for that tag to not exist or if that was a recent Minecraft change, either way it should be fixed now.

I did notice another issue while testing using the region file you sent.  It appears that ice is having some sort of issue:
![iceGlitch](https://user-images.githubusercontent.com/466126/95879436-96d58180-0d33-11eb-9dff-8377aa6b324d.jpg)

I want to see if I can fix that too and then I I'll put out another bug fix release.  (Also, the swamp grass and foliage colors are wrong, but that's a tricky issue that I haven't determined how to fix yet.)

**Comment by turtle2472** [comment] 2020-10-13 15:28
Oooo... that is our Hyperloop test field!  Such an odd chunk with neat stuff.

Thanks for working through this.  We all really appreciate it.

**Comment by skoeven** [comment] 2020-10-14 05:14
A new release is out that should fix both the missing Name tag NPE and ice glitch: [https://github.com/tectonicus/tectonicus/releases/tag/v2.28.4](https://github.com/tectonicus/tectonicus/releases/tag/v2.28.4)

**Comment by turtle2472** [comment] 2020-10-16 00:46
Thanks.  I've downloaded it but I'm having issues with my hypervisor right now which is hindering my testing.  I'm going to see about trying on my Mac and see how that works with this.

**Closed** 2022-03-11 06:23 UTC
