### ISSUE TITLE
Blank (all white) map.html

### ISSUE THREAD

**Issue by Franckovish** [tectonicus/tectonicus#143] opened 2021-02-28 23:48 UTC
After the generation of the map, loading map.html gives me a blank webpage. 

The content of Map0 does include a bunch of image that give me the impression that everything is fine.  But loading the webpage shows nothing of interest.

I'm hosting the result and the config file used at the following address :

http://francoisjanson.com:8080/MyMap2/

**Comment by swbr** [comment] 2021-04-09 09:47
Just as info: The problem is that  `MyMap2/Map0/worldVectors.js` is corrupted, it just contains

```
var Map0_worldVectors =
{

```

No idea why it happened, but it may help the developers if you also add the log file

**Comment by Franckovish** [comment] 2021-04-15 22:30
Good idea.  I added the logfile next to the map.html

**Comment by Franckovish** [comment] 2021-04-15 22:33
Clearly ... this is very bad ... hehe

Outputting world vectors to d:\Tectonicus\MyMap2\Map0\worldVectors.js
java.lang.NullPointerException
	at tectonicus.JsonWriter.jsEscape(Unknown Source)
	at tectonicus.JsonWriter.writeVariable(Unknown Source)
	at tectonicus.TileRenderer.outputWorldVectors(Unknown Source)
	at tectonicus.TileRenderer.output(Unknown Source)
	at tectonicus.TectonicusApp.run(Unknown Source)
	at tectonicus.TectonicusApp.main(Unknown Source)
World vectors done

**Comment by skoeven** [comment] 2021-06-15 05:26
Sorry I haven't had time to get to this until now.  Would it be possible to get a copy of your world?  There are quite a few different errors showing in the log and I'm not sure what the root issue could be.

**Comment by Franckovish** [comment] 2021-06-15 12:28
Sure, I just uploaded the world here : http://francoisjanson.com:8080/MyMap2/world.zip

**Comment by skoeven** [comment] 2021-06-16 03:55
So I was able to render the map.  
![testMap](https://user-images.githubusercontent.com/466126/122155230-c76e3d80-ce23-11eb-81cc-c12dd485110f.jpg)
The reason you weren't able to see it is that map centering is still broken because of the switch to Leaflet from Google Maps (see #102 and #148).  In order to find the rendered tiles you have to scroll the map up for a while, obviously not very usable.  Fixing this is on the todo list.

As far as all of the other errors in your log file the only ones that I was able to reproduce were the ones related to the players. It looks like they don't have Mojang accounts so they all returned null.  That's something I could handle better.

The other errors I'm not sure about.  Did you maybe run Tectonicus on the world while it was open in Minecraft or Minecraft Server?

**Comment by Franckovish** [comment] 2021-06-16 04:03
I am not sure if the log file I gave you was with the server running or not.  I tried both but couldn't see the map (probably because of the reasons you listed)

**Comment by skoeven** [comment] 2022-04-26 20:57
Map centering is fixed in the upcoming 2.29 release.

**Closed by skoeven** 2022-04-26 20:57 UTC
