### ISSUE TITLE
Loaded null player

### ISSUE THREAD

**Issue by sentaidigital** [tectonicus/tectonicus#73] opened 2016-05-04 14:23 UTC
More often than not, I don't get the actual data for a player, just a list of the following:

```
Loading raw player from /Users/franklin/Minecraft/Unseen/playerdata/[uuid-scrubbed].dat
Loaded null
```

If I stop the render and restart it too soon, I'll get "You are only allowed to contact the Mojang session server once per minute per player.  Wait for a minute and try again." but not on all of the players, suggesting that the load player code isn't getting as far as contacting Mojang in some cases.

**Comment by sentaidigital** [comment] 2016-05-04 14:24
Of course, this means I get the following later in the build:

```
No skin for player null
	outputting null
No skin for player null
	outputting null
No skin for player null
Outputted 10 players
Outputting beds to /Users/franklin/Minecraft/Unseen-map/Map0/beds.js
	outputting null's bed
	outputting null's bed
	outputting null's bed

```

**Comment by skoeven** [comment] 2016-05-15 22:18
Does this happen consistently with the same players?  If so, could you post the UUID of one which isn't working?

**Comment by sentaidigital** [comment] 2016-05-15 23:45
Sadly, no.  It's usually all-or-nothing, but occasionally I'll get one.  I thought it might be a caching issue.  That is, if Mojang has the player in cache, it'll show, otherwise I'm SOL.  However, if I log in to the game (which should put my own player data in any cache Mojang might have), I *still* don't get my own player on the map.

**Comment by skoeven** [comment] 2016-05-16 02:05
You might be right about it being a caching issue, except it may not be a Mojang caching issue but a Tectonicus caching issue.  Are you rendering a fresh map each time (i.e. "eraseOutputDir" is set to true)?

**Comment by sentaidigital** [comment] 2016-05-16 02:15
No, the tile and chunk caches are way too useful.  If I stop a run early on and immediately restart, I do get the warning from Mojang about connecting more often than once a minute.

**Comment by skoeven** [comment] 2016-05-16 02:28
Ah, it might very well have something to do with player skin caching then.  I'll do some testing and see what I can figure out.

**Comment by turtle2472** [comment] 2016-05-16 02:32
It is a Tectonicus caching issue.  I never raised it because I keep forgetting about it.  The "fix" for me is to have my scrip delete Cache/skinCache/skins.cache from the output directory.  This forces a fresh skin data the results in proper names for those players who changed their name and the right skins to show.

**Comment by sentaidigital** [comment] 2016-05-16 03:30
This caching issue would break *all* the users at once?

**Comment by skoeven** [comment] 2016-05-16 04:20
Yep.  After looking through the code I think I know what the issue is.  The first time you render a map each player gets a timestamp in the skincache file, then every time after that Tectonicus checks the timestamp to see if it should refresh the player's info.  Since the players generally get close to the same timestamp on the initial render, they all expire at about the same time too.  Unfortunately when I wrote this code 1 year and 8 months ago (according to source control history) I didn't actually provide any way for it to refresh the player info, so after the timestamps expire player name and skin url are defaulting to null.

Anyway, I'll get some code checked in to fix this.

**Closed** 2016-05-16 05:25 UTC

**Comment by sentaidigital** [comment] 2016-05-16 06:39
Thanks for fixing it.  Until the next release, I'll try @turtle2472's solution of deleting the player skin cache.
